language: objective-c
osx_image: xcode7.3

install:
  - carthage update Nimble Quick --platform iOS --no-use-binaries
  - carthage update Alamofire Gloss --no-use-binaries

script:
  - xcodebuild test -project Restofire.xcodeproj
    -scheme Restofire-iOS
    -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
    -destination 'name=iPhone 6,OS=9.3'

  - xcodebuild -project Restofire.xcodeproj
    -scheme Restofire-Mac
    -sdk macosx ONLY_ACTIVE_ARCH=NO
    -destination 'arch=x86_64'

  - xcodebuild -project Restofire.xcodeproj
    -scheme Restofire-watchOS
    -sdk watchsimulator ONLY_ACTIVE_ARCH=NO
    -destination 'name=Apple Watch - 38mm,OS=2.2'

  - xcodebuild -project Restofire.xcodeproj
    -scheme Restofire-tvOS
    -sdk appletvsimulator ONLY_ACTIVE_ARCH=NO
    -destination 'name=Apple TV 1080p,OS=9.2'
